Endpoint for nps
zero-filtre/zerofiltre-blog-backend pull request #82
Opened 2024-07-17 10:23 UTC by FellahAbdel

2024-07-18 07:10 UTC, imphilippesimo commented on pom.xml
> +            </plugin>
Pas de ce plugin pour le moment

2024-07-18 07:14 UTC, imphilippesimo commented on pom.xml
> +                        q
Retirer

2024-07-18 07:29 UTC, imphilippesimo commented on src/main/java/tech/zerofiltre/blog/domain/course/model/Review.java
> +        if(!isDeletion && currentUserId != existingReview.getUserId()) {
boolean isAuthor = currentUserId != existingReview.getUserId;

2024-07-18 07:30 UTC, imphilippesimo commented on src/main/java/tech/zerofiltre/blog/domain/course/model/Review.java
> +        // Non-Admin user are not allowed to delete a review
remove useless comments

2024-07-18 07:31 UTC, imphilippesimo commented on src/main/java/tech/zerofiltre/blog/domain/course/model/Review.java
> +    }
Utiliser lombok pour le pattern builder

2024-07-18 07:32 UTC, imphilippesimo commented on src/main/java/tech/zerofiltre/blog/domain/course/use_cases/review/CreateReview.java
> +import tech.zerofiltre.blog.domain.course.ReviewProvider;
Delete this useless class

2024-07-18 07:32 UTC, imphilippesimo commented on src/main/java/tech/zerofiltre/blog/domain/course/use_cases/review/DeleteReview.java
> +        reviewProvider.deleteById(id);
delete class

2024-07-18 07:44 UTC, imphilippesimo commented on src/main/java/tech/zerofiltre/blog/infra/providers/database/course/DBReviewProvider.java
> +        Optional<ReviewJPA> existingReviewOpt = reviewJPARepository.findById(review.getReviewId());
Opt c'est pas lisible

2024-07-18 07:44 UTC, imphilippesimo commented on src/main/java/tech/zerofiltre/blog/infra/providers/database/course/DBReviewProvider.java
> +            // Update fields of the existing review
remove useless comments

2024-07-21 09:22 UTC, imphilippesimo commented on src/main/java/tech/zerofiltre/blog/infra/providers/database/course/DBReviewProvider.java
> +        Optional<ReviewJPA> existingReviewOpt = reviewJPARepository.findById(review.getReviewId());
Renommer en 'exsitingReview' simplement

2024-07-21 09:23 UTC, imphilippesimo commented on src/test/java/tech/zerofiltre/blog/infra/providers/database/course/DBReviewProviderTest.java
> +    @DisplayName("")
Enlever si ne contient rien

2024-07-21 09:24 UTC, imphilippesimo commented on src/test/java/tech/zerofiltre/blog/infra/providers/database/course/DBReviewProviderTest.java
> +    @DisplayName("JUnit test given review when ")
Enlever displayname si le nom du test est court et compréhensible

2024-07-21 09:26 UTC, imphilippesimo commented on src/test/java/tech/zerofiltre/blog/domain/course/model/ReviewTest.java
> +        verify(reviewProvider, times(1)).save(review);
On veut vérifier que l'appel à save se fait sans execeptions. Il faut alors utiliser : 
assertThatNoExceptionIsThrown

2024-07-21 09:47 UTC, imphilippesimo requested changes

2024-07-21 09:47 UTC, imphilippesimo commented on src/test/java/tech/zerofiltre/blog/domain/course/model/ReviewTest.java
> +        verify(reviewProvider, times(1)).save(review);
AssertThatNoExceptionIsThrown à la place de verify

2024-07-21 09:47 UTC, imphilippesimo commented on src/test/java/tech/zerofiltre/blog/domain/course/model/ReviewTest.java
> +        verify(reviewProvider, times(1)).save(review);
Ce test n'est pas pertinent car on a déjà un test qui montre seul l'auteur d'une revue peut la modifier . update_works_if_the_update_is_the_owner_of_review

2024-07-21 09:47 UTC, imphilippesimo commented on src/test/java/tech/zerofiltre/blog/domain/course/model/ReviewTest.java
> +                .userProvider(userProvider)
il faut passer le reviewProvider à null et le userId à 0 pour montrer que tu n'utiliseras pas userProvider et que aucun utilisateur n'est connecté (id non connu = 0)

2024-07-21 09:47 UTC, imphilippesimo commented on src/test/java/tech/zerofiltre/blog/domain/course/model/ReviewTest.java
> +    void find_by_id_throws_ResourceNotFoundException_if_user_not_found() {
Ceci n'est pas une règle métier.
Tout utilisateur non connecté doit pouvoir consulter les revues. 
Qui est l'utilisateur recherché dans revue ? (userId) est ce l'auteur de la revue ou celui qui consulte ?
Il faut différencier les deux!

2024-07-21 09:47 UTC, imphilippesimo commented on src/test/java/tech/zerofiltre/blog/domain/course/model/ReviewTest.java
> +    void init_saves_review_if_user_is_found() throws ResourceNotFoundException {
Une revue ne peut être initiée par un utilisateur si et seulement si il a accès au cours dont le chapitre en fait partie.

Qui est l'utilisateur recherché dans revue ? (userId) est ce l'auteur de la revue ou celui qui consulte ?
Il faut différencier les deux!

2024-07-23 07:16 UTC, imphilippesimo commented on src/test/java/tech/zerofiltre/blog/infra/providers/database/course/DBReviewProviderTest.java
> +public class DBReviewProviderTest {
Transformer cette classe en test d'intégration.
Qui vérifier que l'ajout d'une reviexw est belle et bien prise en compte dans la BD.

2024-07-23 07:41 UTC, imphilippesimo commented on src/test/java/tech/zerofiltre/blog/domain/course/model/ReviewTest.java
> +public class ReviewTest {
Rajouter des tests pour vérifier qu'un utilisateur qui n'est ni pro, ni enrollé ne peut faire une review sur un chapitre

2024-07-23 07:58 UTC, imphilippesimo requested changes
Vérifier que le user est bel et bien enrollé via les test dd'intégration
Règle métier supp: Si init avec le meme id de chapitre alors call update

2024-07-29 08:01 UTC, imphilippesimo requested changes
Hello, prends en compte chacun de mes commentaires.
Puis il va falloir que tu crées des endpoints sous postman pour tester foncitonnellement l'init, la mise à jour, la récupération par id /all et la suppression.

2024-08-02 06:05 UTC, imphilippesimo requested changes
On y est presque ! 
Encore un peu d'efforts, prendre en compte mes commentaires.

2024-08-02 06:05 UTC, imphilippesimo commented on src/main/java/tech/zerofiltre/blog/infra/entrypoints/rest/course/ReviewController.java
> +        Optional<Review> existingReview = reviewProvider.findByAuthorIdAndChapterId(authorReviewId, chapterId);
Pas besoin de rechercher la review existante dans le controller, en effet c'est déjà fait dans ReviewDBProvider.save
D'ailleurs j'aurais préférré que la logique en question soit faite dans la classe Review et pas dans l'adaptateur.

2024-08-02 06:05 UTC, imphilippesimo commented on src/main/java/tech/zerofiltre/blog/domain/course/model/Review.java
> +    public Review update() throws ForbiddenActionException, ResourceNotFoundException {
Je préfère que ce soit dans cette classe que tu ailles chercher la revue existante, la mette à jour avant de la sauvegarder.
Le but centraliser l'intelligence et la tester dans la classe review. (Le contrôleur ce n'est qu'un aiguilleur, le provider ce n'est qu'un ... fournisseur), c'est le modèle de domaine (Review) qui doit être intelligent.

2024-08-02 06:05 UTC, imphilippesimo commented on src/main/java/tech/zerofiltre/blog/infra/providers/database/course/DBReviewProvider.java
> +        if (existingReview.isPresent()) {
J'aurais préféré que la logique en question soit faite dans la classe Review et pas dans l'adaptateur(provider).

2024-08-02 11:52 UTC, FellahAbdel commented on src/main/java/tech/zerofiltre/blog/infra/entrypoints/rest/course/ReviewController.java
> +        Optional<Review> existingReview = reviewProvider.findByAuthorIdAndChapterId(authorReviewId, chapterId);
J'ai deplacé la logique dans Review.init

2024-08-02 13:49 UTC, FellahAbdel commented on src/main/java/tech/zerofiltre/blog/domain/course/model/Review.java
> +    public Review update() throws ForbiddenActionException, ResourceNotFoundException {
Parfait, j'ai augmenté l'intelligence de la review

2024-08-04 07:34 UTC, imphilippesimo approved these changes

2024-08-04 07:34 UTC, merged