[628] Stripe subscription cancelled
zero-filtre/zerofiltre-blog-backend pull request #83
Opened 2024-07-18 12:59 UTC by Philiform

2024-07-23 21:01 UTC, imphilippesimo requested changes

2024-07-23 21:01 UTC, imphilippesimo commented on src/test/java/tech/zerofiltre/blog/infra/providers/api/stripe/SubscriptionEventHandlerTest.java
> +            when(userProvider.userOfId(15L)).thenReturn(Optional.of(user));
Test à modifier selon le commentaire d'en dessous

2024-07-30 17:45 UTC, Philiform commented
Les cas d'utilisation 3 et 4 concernent tous les deux le paiement en 3 fois d'un cours  qui est terminé lorsqu'on reçoit l'événement.

J'ai donc fait un test unitaire pour ces 2 cas d'utilisation.

2024-08-02 09:46 UTC, Philiform commented
J'ai ajouté un test dans "SubscriptionEventHandlerTest" pour vérifier que si l'utilisateur n'existe pas l'application ignore l'événement.

2024-08-04 07:33 UTC, imphilippesimo approved these changes

2024-08-04 07:33 UTC, merged